CREATE TABLE [frm].[FormType]
(
	[FormTypeId] INT IDENTITY(1001,1) NOT NULL,
	[Title] VARCHAR(256) NOT NULL,
	[CreateTimestamp] DATETIME2(4) CONSTRAINT [DF_FormType_CreateTimestamp] DEFAULT(SYSUTCDATETIME()) NOT NULL,
	[UpdateTimestamp] DATETIME2(4) CONSTRAINT [DF_FormType_UdateTimestamp] DEFAULT(SYSUTCDATETIME()) NOT NULL,
	CONSTRAINT [PK_FormType] PRIMARY KEY CLUSTERED ([FormTypeId] DESC)
)
