CREATE TABLE [cfg].[Item]
(
	[ItemId] UNIQUEIDENTIFIER NOT NULL,
	[IsPublic] BIT CONSTRAINT [DF_Item_IsPublic] DEFAULT 0 NOT NULL,
	[Code] VARCHAR(512) NOT NULL,
	[Data] VARCHAR(MAX) NOT NULL,
	[CreateTimestamp] DATETIME2(4) CONSTRAINT [DF_Item_CreateTimestamp] DEFAULT(SYSUTCDATETIME()) NOT NULL,
	[UpdateTimestamp] DATETIME2(4) CONSTRAINT [DF_Item_UpdateTimestamp] DEFAULT(SYSUTCDATETIME()) NOT NULL,
	CONSTRAINT [PK_Item] PRIMARY KEY CLUSTERED ([ItemId])
)

GO

CREATE UNIQUE INDEX [IX_Item_Code] ON [cfg].[Item] ([Code])
