CREATE TABLE [lg].[Trace]
(
	[TraceId] UNIQUEIDENTIFIER NOT NULL,
	[EventCode] VARCHAR(200) NOT NULL,
	[Message] NVARCHAR(2000) NOT NULL,
	[Data] NVARCHAR(MAX) NOT NULL,
	[Timestamp] DATETIME2(4) CONSTRAINT [DF_Trace_Timestamp] DEFAULT SYSUTCDATETIME() NOT NULL,
	CONSTRAINT [PK_Trace] PRIMARY KEY CLUSTERED ([TraceId])
)
WITH (DATA_COMPRESSION = PAGE)

GO

CREATE INDEX [IX_Trace_Timestamp] ON [lg].[Trace] ([Timestamp] DESC)

GO

CREATE INDEX [IX_Trace_EventCode] ON [lg].[Trace] ([Timestamp] DESC)
